### ISSUE TITLE
"This repo contains azure OpenAI, OpenAI, and OpenRouter, modify the import inside src/server.ts to switch between which one to use."

### ISSUE THREAD

**Issue by 619** [RetellAI/retell-custom-llm-node-demo#2]
# Modify how? #

**Comment by weijia-yu** [comment]
You can import different LLM client and modify this line
https://github.com/adam-team/retell-backend-node-demo/blob/41bec67ff5829a6e68ddf2e94a1f26d76d7d4cea/src/server.ts#L35
